# Generated by Django 2.1.4 on 2018-12-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='username',
        ),
    ]
